name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential libncurses5 libstdc++6

      - name: Install Buildozer & dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app
          path: bin/*.apk
