name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev libjpeg-dev libncurses5
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Accept Android Licenses and Setup SDK
        run: |
          mkdir -p $HOME/.android
          echo '### User Sources for Android SDK Manager' > $HOME/.android/repositories.cfg
          yes | buildozer android update

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PDFViewerApp
          path: bin/*.apk
