name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential libstdc++6 libncurses6

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          yes | sdkmanager --licenses || true

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app
          path: bin/*.apk
