name: Clean Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip openjdk-8-jdk python3-pip
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app
          path: bin/*.apk
