name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev libjpeg-dev libncurses5 wget
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv buildozer

      - name: Setup Android SDK manually
        run: |
          mkdir -p $HOME/Android/cmdline-tools
          cd $HOME/Android/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android --licenses
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Build APK with Buildozer
        env:
          ANDROIDSDK: $HOME/Android
          ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b
          PATH: $HOME/Android/cmdline-tools/latest/bin:$HOME/Android/platform-tools:$PATH
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PDFViewerApp
          path: bin/*.apk
