name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential \
                              libncurses5 libstdc++6 libffi-dev libssl-dev curl git

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/Android/cmdline-tools
          cd $HOME/Android/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip tools.zip -d latest
          rm tools.zip

      - name: Accept licenses and install SDK components
        run: |
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android \
            "platform-tools" "platforms;android-33" "build-tools;33.0.0"
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/Android

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/Android" >> $GITHUB_ENV
          echo "PATH=$HOME/Android/platform-tools:$HOME/Android/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app
          path: bin/*.apk

      - name: Show logs on failure
        if: failure()
        run: cat ./.buildozer/android/platform/build/*/build.log || echo "No build log found"
